# Generated by Django 5.0.4 on 2024-05-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0005_productprice_upc"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="maximum 200 characters", max_length=200
                    ),
                ),
                ("address", models.CharField(max_length=1024)),
                ("stockroom_code", models.CharField(max_length=8)),
            ],
            options={
                "ordering": ("stockroom_code",),
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "shortage_threshold",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "product_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="products.productprice",
                    ),
                ),
                (
                    "stockroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="inventory.stockroom",
                    ),
                ),
            ],
            options={
                "ordering": ("sku",),
                "unique_together": {("product_price", "stockroom")},
            },
        ),
    ]
