# Generated by Django 5.0.4 on 2024-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="variation",
        ),
        migrations.RemoveField(
            model_name="productprice",
            name="variation_option",
        ),
        migrations.AddField(
            model_name="product",
            name="variation",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.variation"
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="variation_option",
            field=models.ManyToManyField(blank=True, to="products.variationoption"),
        ),
    ]
