# Generated by Django 5.0.4 on 2024-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_categoryimage_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="upc",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
